name: Test
on: push

jobs:
  test:
    name: Test
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go: [ 1.17, 1.18, 1.19 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          check-latest: true
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ matrix.go }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ runner.os }}-${{ matrix.go }}-
      - run: go mod download
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - run: go vet ./...
      - run: go test -race ./...
      - run: go build
